# How often the program checks for new emails (in minutes)
order_check_interval: 1

# How often the alarm is sounded for when a new order happens (in milliseconds)
alarm_interval: 2000

# How long the alarm is activated for (in milliseconds)
alarm_on_duration: 1000

# The pin that the button to turn off the alarm is connected to on the pi
button_pin: 4

# The pin that the alarm relay is connected to on the pi
alarm_relay_pin: 17
